### ISSUE TITLE
Remove pausePlayerForcibly:

### ISSUE THREAD

**Issue by saiday** [StreetVoice/HysteriaPlayer#100]
It's too hard to use, bad design.

**Comment by praveenkumartapmobi** [comment]
So? Are you going to introduce anything instead this?

**Comment by saiday** [comment]
Yes, a pause method with explicitly intention.

**Comment by newbdez33** [comment]
need a hand?

**Comment by saiday** [comment]
@newbdez33 sure! it would be great if you could do this

**Comment by newbdez33** [comment]
My frist thought:

1. move `pausePlayerForcibly:` to Deprecation section and flag it as deprecated.
2. add `pauseReasonForced = true` to `pause:` method

any suggestion?

**Comment by saiday** [comment]
Have no any other suggestions, I totally agree with you.
a useful `DEPRECATED_MSG_ATTRIBUTE` is what we need.

**Comment by newbdez33** [comment]
Sure. I will start a pull request later.
