### ISSUE TITLE
Delegate message when play empty sound

### ISSUE THREAD

**Issue by iTSangarDEV** [StreetVoice/HysteriaPlayer#101]
Is necessary send delegate message `hysteriaPlayerCurrentItemChanged` when emptySoundPlaying is YES?

```objective-c
if (newPlayerItem != (id)[NSNull null]) {
        [newPlayerItem addObserver:self forKeyPath:@"loadedTimeRanges" options:NSKeyValueObservingOptionNew context:nil];
        [newPlayerItem addObserver:self forKeyPath:@"status" options:NSKeyValueObservingOptionNew context:nil];
            
        if ([self.delegate respondsToSelector:@selector(hysteriaPlayerCurrentItemChanged:)]) {
                [self.delegate hysteriaPlayerCurrentItemChanged:newPlayerItem];
        }
            self.emptySoundPlaying = NO;
 }
```

can be? 

```objective-c
if ([self.delegate respondsToSelector:@selector(hysteriaPlayerCurrentItemChanged:)] && !self.emptySoundPlaying) {
            [self.delegate hysteriaPlayerCurrentItemChanged:newPlayerItem];
}
```

**Comment by saiday** [comment]
Empty sound is a hack for buffering long term first remote item, is there any reason that you want to handle it?

**Comment by iTSangarDEV** [comment]
As empty sound is not a real sound and finality of method `hysteriaPlayerCurrentItemChanged:` is usually update the interface, so I think that can be called only when real item is changed.


I found this necessity when trying transform result of `getHysteriaIndex:` in Integer on `Swift` and empty sound return null

```swift
let index = Int(hysteriaPlayer.getHysteriaIndex(hysteriaPlayer.getCurrentItem()))
```

**Comment by iTSangarDEV** [comment]
But looking around I found solution from check if is null (emptySoundPlaying == YES):

```swift
if let index: NSNumber = hysteriaPlayer.getHysteriaIndex(hysteriaPlayer.getCurrentItem()) {
  // now I can use Int(index)
}
```

Thank you for helping me to think better what I wanted, you can close this issue.

**Comment by saiday** [comment]
Yeah, great approach to find index. Glad to hear that.
