### ISSUE TITLE
`removeItemAtIndex` issue when [hysteriaPlayer enableMemoryCached:NO];

### ISSUE THREAD

**Issue by praveenkumartapmobi** [StreetVoice/HysteriaPlayer#103]
Hi,

The method `removeItemAtIndex` will not work when `[hysteriaPlayer enableMemoryCached:NO]`

So, by that time how could a item removed from the Player. I have just work around by your code and modified something like below. I don't know whether its acceptable or not. Kindly, check this issue and try to reproduce it.

    - (void)removeItemAtIndex:(NSInteger)index
    {
        for (AVPlayerItem *item in [NSArray arrayWithArray:self.playerItems]) {
            NSInteger checkIndex = [[self getHysteriaIndex:item] integerValue];
            if (checkIndex == index) {
                NSMutableArray *playerItems = [NSMutableArray arrayWithArray:self.playerItems];
                [playerItems removeObject:item];
                self.playerItems = playerItems;
            
                if ([self.audioPlayer.items indexOfObject:item] != NSNotFound) {
                    [self.audioPlayer removeItem:item];
                }
            } else if (checkIndex > index) {
                [self setHysteriaIndex:item key:[NSNumber numberWithInteger:checkIndex -1]];
            }
        }
    
        // Remove item from Player
        [self removeQueuesAtPlayer];
    
        for (AVPlayerItem *item in [NSArray arrayWithArray:self.audioPlayer.items]) {
            NSInteger checkIndex = [[self getHysteriaIndex:item] integerValue];
            if (checkIndex == index) {
                NSMutableArray *playerItems = [NSMutableArray arrayWithArray:self.playerItems];
                [playerItems removeObject:item];
                self.playerItems = playerItems;
            
                if ([self.audioPlayer.items indexOfObject:item] != NSNotFound) {
                    [self.audioPlayer removeItem:item];
                }
            } else if (checkIndex > index) {
                [self setHysteriaIndex:item key:[NSNumber numberWithInteger:checkIndex -1]];
            }
        }
    }

**Comment by saiday** [comment]
Hi, @praveenkumartapmobi 
Please kindly check this branch, the patch should fix your issue. If so, I would merge to master and redeploy to CocoaPods again (but hold the version at 2.1.6).

**Comment by praveenkumartapmobi** [comment]
Yes, its perfect. You can merge it. I just added some unwanted lines in my code,

`[self removeQueuesAtPlayer]`

and

    NSMutableArray *playerItems = [NSMutableArray arrayWithArray:self.playerItems];
    [playerItems removeObject:item];
    self.playerItems = playerItems;

    if ([self.audioPlayer.items indexOfObject:item] != NSNotFound) {
                
    }

**Comment by saiday** [comment]
Thank you for your testing.

Merged, if you integrate HysteriaPlayer via CocoaPods, you have to remove HysteriaPlayer pod directory and re-install it.

**Comment by praveenkumartapmobi** [comment]
No, i am not using CocoaPods. I'll replace or change the code. No Problem.

Thanks.
