### ISSUE TITLE
Audio pause automatically during bad network(ex. edge) instead of buffering. 

### ISSUE THREAD

**Issue by kevinlin505** [StreetVoice/HysteriaPlayer#113]
When I testing the player on edge network the audio automatically pauses.
This could be the same issue reported at [#112](https://github.com/StreetVoice/HysteriaPlayer/issues/112).

Steps:
Playing .... --> Buffering... --> user pauses --> user resumes --> playing... then if the audio buffers again it pauses by itself. It seems like this only happens after a user pauses and plays the current audio at some point.

**Comment by kevinlin505** [comment]
@saiday Any updates on this issue?

**Comment by saiday** [comment]
Fixed, please check 2.1.8 release!
