### ISSUE TITLE
HysteriaPlayerStatus=Playing after end of audio

### ISSUE THREAD

**Issue by davros1970** [StreetVoice/HysteriaPlayer#118]
I got the hysteriaPlayerDidReachEnd callback, and in the callback, I query the status and it is reported as HysteriaPlayerStatus=Playing. That seems like a bug to me.

**Comment by saiday** [comment]
Hi @davros1970, which HysteriaPlayer version you using?

I checked 2.1.8 codebase, all `hysteriaPlayerDidReachEnd` delegate callback called after pausing.

**Comment by savasadar** [comment]
hi @saiday, @davros1970 is right. When hysteriaPlayerDidReachEnd delegate called, I check '[HysteriaPlayer sharedInstance].isPlaying' and it came still 'true' (playing). But track was over.

**Comment by saiday** [comment]
@savasadar @davros1970 thank you, investigating.

**Comment by savasadar** [comment]
Is there any solution for this?
