### ISSUE TITLE
Rapid Fire Play/Pause Loop

### ISSUE THREAD

**Issue by mtorcutt** [StreetVoice/HysteriaPlayer#119]
I have one user that is reporting the player rapid fire playing/pausing. 

This can be seen in our Mixpanel records as follows.
<img width="307" alt="screen shot 2016-05-25 at 3 42 00 pm" src="https://cloud.githubusercontent.com/assets/5586728/15555735/ae4aa518-228f-11e6-802c-f7f0356c9ef3.png">

**Comment by saiday** [comment]
@mtorcutt Your records showing there's something wrong on playback, but I don't think this could relate to HysteriaPlayer.

You can check your playback controls first.

Need more detail.

**Comment by mtorcutt** [comment]
@saiday if I get any more information – I will post it here. 

I cannot reproduce this either but, we were able to find records of it happening in MixPanel.
