### ISSUE TITLE
notificationPost interuption crash 

### ISSUE THREAD

**Issue by devluyy** [StreetVoice/HysteriaPlayer#120]
![image](https://cloud.githubusercontent.com/assets/11494557/15737129/ece7ff6c-28d6-11e6-8269-5d8c6f3392e7.png)

**Comment by saiday** [comment]
Hi @devluyy, can you attach full stack track?

Thanks

**Comment by devluyy** [comment]
![_b76 49ylbucsawul12x1fg](https://cloud.githubusercontent.com/assets/11494557/15737241/a9bdcb26-28d7-11e6-9ba4-f8927dbfa77b.jpg)

**Comment by devluyy** [comment]
@saiday i find this obeserver don't remove in function AVAudioSessionNotification

**Comment by saiday** [comment]
@devluyy Yes, you're right. I found it too. gotta fix it.

Hence, this issue could happen when you `deprecatePlayer()`, have you ever use `deprecatePlayer()` in your codebase?

**Comment by devluyy** [comment]
@saiday yes! i use deprecatePlayer() in viewWillDisappear()

**Comment by devluyy** [comment]
@saiday cool !

**Comment by saiday** [comment]
If you're using CocoaPods, a new version `2.1.9` is what you need.

Thank you again.
