### ISSUE TITLE
Sometimes app freeze on streaming

### ISSUE THREAD

**Issue by kjpolaszek** [StreetVoice/HysteriaPlayer#121]
When i use HysteriaPlayer for streaming audio, sometimes app freezing after change to new AVPlayerItem. 
Place were app stop is
`[self.audioPlayer insertItem:item afterItem:nil];`

**Comment by saiday** [comment]
Thank you for your PR

**Comment by adeelmiraj** [comment]
@saiday I'm also facing the same problem. Has this been resolved?
