### ISSUE TITLE
Player don't work on debug configuration in pods

### ISSUE THREAD

**Issue by kjpolaszek** [StreetVoice/HysteriaPlayer#123]
I added HysteriaPlayer to my project by pods and on debug configuration player don't work, when i moved library directly to my project omitting pods, it work properly.

**Comment by saiday** [comment]
I using CocoaPods to integrate HysteriaPlayer into my project as well, I have no such issue, can you reproduce it?

**Comment by kjpolaszek** [comment]
I don't know why, but if i changed build configuration from debug to release in schema it work properly. Only on debug using CocoaPods this issue appear.

**Comment by saiday** [comment]
oh, so that's about CocoaPods configurations, you should use cocoapods generated build configuration as your target build configuration under project section. [ref](http://stackoverflow.com/a/16703468/1554531)

You are welcome.
