### ISSUE TITLE
Is there any way to go forward x seconds in the current playing item?

### ISSUE THREAD

**Issue by arcioneo** [StreetVoice/HysteriaPlayer#124]
I just want to do this like the itunes podcast player, does this exists on hysteriaplayer?

**Comment by saiday** [comment]
@arcioneo https://github.com/StreetVoice/HysteriaPlayer/blob/master/HysteriaPlayer/HysteriaPlayer.h#L162-L163

These two methods are just simple wrappers of AVAudioPlayer's methods, is this what you're looking for?
