### ISSUE TITLE
When add All exceptions, run in simulator is cash!

### ISSUE THREAD

**Issue by ldhios** [StreetVoice/HysteriaPlayer#128]
![image](https://cloud.githubusercontent.com/assets/9722423/20742493/50f95466-b70b-11e6-9b1d-37fbf7f96743.png)

![image](https://cloud.githubusercontent.com/assets/9722423/20742530/8c13d4d6-b70b-11e6-8cea-1685a2d8ea26.png)

**Comment by saiday** [comment]
@ldhios thank you for reporting this issue. Now, `master` branch should be fine.

@kjpolaszek hi, this issue seems relating to https://github.com/StreetVoice/HysteriaPlayer/pull/122, do you have any suggestion?
Going to revert this PR, sorry about that.
