### ISSUE TITLE
the part4  is 404 not found

### ISSUE THREAD

**Issue by GPX-NSlog** [StreetVoice/HysteriaPlayer#132]
i want to read part4 to resolve my problem,please update it, thanks

**Comment by patrickjquinn** [comment]
You should provide direct logs and line numbers if you can, makes life easier for all involved 👍

**Comment by saiday** [comment]
@GPX-NSlog 
Actually, I scheduled to write that post but didn't make it, where did you get the link?

If you still remember, what's the topic of that post?
