### ISSUE TITLE
Playing a track dynamically after a current Track

### ISSUE THREAD

**Issue by shaikshabana** [StreetVoice/HysteriaPlayer#55]
Hi,
I have a search in my application and selected track should added to Audio Queue at current item and have to play newly added track.
As asyncSetupSourceGetter adds all track to the Audio Queue at once how can i achieve this one. 
Thanks,
Shabana

**Comment by saiday** [comment]
Simply modify your asyncSetupSourceGetter(in 2.1.0 is deprecated, use `hysteriaPlayerAsyncSetUrlForItemAtIndex:preBuffer:` delegate method instead) to return correct URLs, and make sure you increase your `itemsCount` by delegate or property.

If you use the index of current item, then you have to call `moveItemFromIndex:toIndex:` method for those items that behind the item you just inserted.
