### ISSUE TITLE
Percentage of File Buffered

### ISSUE THREAD

**Issue by dyelax** [StreetVoice/HysteriaPlayer#60]
It would be useful to have a delegate method that gives both the current file's total size and how much data has been loaded up to this point. This could be used to calculate the percentage of the file that has buffered, which would be nice for UI to be able to show the user how far ahead the buffer is.

**Comment by tarzon** [comment]
I am also interested in this ... Please add it.

**Comment by saiday** [comment]
I'm planning `2.1` release features, if everything goes well, then I would have time to add this delegate to it. 

Hopefully.

**Comment by saiday** [comment]
We do have a delegate method `hysteriaPlayerCurrentItemPreloaded:` that meets your requirements.

Example:
```
- (void)hysteriaPlayerCurrentItemPreloaded:(CMTime)time
{
    NSLog(@"current item pre-loaded time: %f", CMTimeGetSeconds(time));
}
```

**Comment by tarzon** [comment]
Thanks @saiday . This is just awesome.
