### ISSUE TITLE
@interface HysteriaPlayer () 

### ISSUE THREAD

**Issue by lilin87788** [StreetVoice/HysteriaPlayer#74]
能不能把这个里面的一些属性暴露在.h 外面，当我继承HysteriaPlayer 想做一些自己的操作时，拿不到那些属性，使得我不得不在你的源码上修改。不知道我有没有说清楚

**Comment by saiday** [comment]
可以討論看看啊，會用 Class Extension 的方式寫在 .m 裡面是認為這些應該是 private property，不曉得你想要存取哪個 property？

**Comment by lilin87788** [comment]
相关的问题我已经解决了，不需要修改你现在的代码，可能会有一个基于这个播放器的app 上架，上面会注明：关于HysteriaPlayer 开源相关，打扰了。。。

**Comment by saiday** [comment]
好！沒問題！
