### ISSUE TITLE
moveItemFromIndex is not working

### ISSUE THREAD

**Issue by praveenkumartapmobi** [StreetVoice/HysteriaPlayer#77]
Hello,

I have created one app using this MusicPlayer Library. Everything works fine here. I have listed all the songs in Table. And, i have implemented Re-arranging song items in using [this tutorial](http://www.raywenderlich.com/63089/cookbook-moving-table-view-cells-with-a-long-press-gesture)

Everything works fine here. But, whenever i implemented the code for re arranging the items in `HysteriaPlayer` using below code,

        case UIGestureRecognizerStateChanged: {
            .....
            .....
            if (indexPath && ![indexPath isEqual:sourceIndexPath]) {
                
                // ... update data source.
                [songRecords exchangeObjectAtIndex:indexPath.row withObjectAtIndex:sourceIndexPath.row];
                
                // ... updating musicplayer datasource
                [[HysteriaPlayer sharedInstance] moveItemFromIndex:indexPath.row toIndex:sourceIndexPath.row];
                
                // ... move the rows.
                [self.musicTableView moveRowAtIndexPath:sourceIndexPath toIndexPath:indexPath];
                
                // ... and update source so it is in sync with UI changes.
                sourceIndexPath = indexPath;
            }
            break;
        }

output of the re-ordered items not coming. What might be the issue? Kindly, guide me..

**Comment by saiday** [comment]
@praveenkumartapmobi If you mean `HysteriaPlayer`'s queued items is not output properly. Make sure you also modify the returning items from source getter block on these two method.
either this
```
- (void)setupSourceGetter:(SourceSyncGetter)itemBlock ItemsCount:(NSUInteger) count;
```
or
```
- (void)asyncSetupSourceGetter:(SourceAsyncGetter)asyncBlock ItemsCount:(NSUInteger)count;
```

Reopen if the answer is not what you looking for.

**Comment by praveenkumartapmobi** [comment]
Hello Saiday,

As [new version (2.1.5)](https://github.com/StreetVoice/HysteriaPlayer/releases/tag/2.1.5) released with lot of new methods and implementations. How do i handle this issue?

Like, i've populated all my song data in a TableView. User can pick a song. So, while playing a song, he/she can rearrange it. If the user rearrange the current playing song, the index of the current items are not changing (I have debugged this)

So, how can i manually reset the Index of current song with `HysteriaOrder` method
