### ISSUE TITLE
Conflict when using in swift

### ISSUE THREAD

**Issue by tcalin** [StreetVoice/HysteriaPlayer#85]
Hi,
I get the following messages when trying to integrate HysteriaPlayer in a swift project
Objective-C method 'hysteriaPlayerNumberOfItems' provided by method 'hysteriaPlayerNumberOfItems()' conflicts with optional requirement method 'hysteriaPlayerNumberOfItems()' in protocol 'HysteriaPlayerDataSource'

for this signature
`override func hysteriaPlayerNumberOfItems() -> Int`

Objective-C method 'hysteriaPlayerURLForItemAtIndex:preBuffer:' provided by method 'hysteriaPlayerURLForItemAtIndex(_:preBuffer:)' conflicts with optional requirement method 'hysteriaPlayerURLForItemAtIndex(_:preBuffer:)' in protocol 'HysteriaPlayerDataSource'

for this signature
`override func hysteriaPlayerURLForItemAtIndex(index: Int, preBuffer: Bool) -> NSURL`

Any help would be appreciated!
Thanks

**Comment by saiday** [comment]
How you integrate HysteriaPlayer to your swift project?

**Comment by tcalin** [comment]
I included `#import "HysteriaPlayer.h"` into TARGET-Bridging-Header.h
Anyway the issue seems solved and everything working as expected after removing the `override` in front of methods's signature.

**Comment by saiday** [comment]
:dancers:
