### ISSUE TITLE
how to adjust audioPlayer's volume

### ISSUE THREAD

**Issue by zhaoxuezhi888** [StreetVoice/HysteriaPlayer#87]
I have multiple volume the same time , I want to control the volume of the AVPlayer relative to other audio output,I add a property in HysteriaPlayer.h
@property (nonatomic,assign) float volume; 

and in HysteriaPlayer.m file,I add the property:
-(float)volume{
    if(self.audioPlayer!=nil){
        return self.audioPlayer.volume;
    }
    else{
        return 0;
    }
}
- (void)setVolume:(float)volume
{
     if(self.audioPlayer!=nil){
        if (self.volume != volume) {
            self.volume = volume;
            self.audioPlayer.volume = volume;
        }
     }
     else{
         self.volume = volume;
     }
}

but It don't work,how can I do? thanks

**Comment by saiday** [comment]
HysteriaPlayer had no behaviours on volume, so it should works like normal AVAudioPlayer.

Your approach and codes looks okay in my opinion, and I suggest you to check the state of `audioPlayer` and `currentItem`, ensure the time you set the volume is `ReadyToPlayer`.
