### ISSUE TITLE
play in iPod

### ISSUE THREAD

**Issue by Phil0529** [StreetVoice/HysteriaPlayer#91]
my code in iphone and simulator can play. but in the ipod ,the KVO observe keyPath only is currentItem and rate . the "loadedTimeRanges" not appear;  the version of the ipod is 8.4.1  and iphone 9.1.2

**Comment by saiday** [comment]
You mean the version of iPod is iOS 8.4.1 and iOS 9.1.2 right? Is there any iOS version can work that you've tested?

I'm not sure what *not appear* you mentioned exactly happened. Never went into `loadedTimeRanges`? 

If possible, you should give us more informations. It can be HysteriaPlayer logs inside your console.

**Comment by Phil0529** [comment]
ok,  a m3u8 format stream music  in ipod 8.4.1 did not work. but in iphone 9.1.2 can play normally. I don't know is the question is ipod or the version .     the stream is normally play in the system player

**Comment by Phil0529** [comment]
can i reply it in this with the question?

At 2015-10-09 17:50:13, "Saiday" <notifications@github.com> wrote:


You mean the version of iPod is iOS 8.4.1 and iOS 9.1.2 right? Is there any iOS version can work that you've tested?

I'm not sure what not appear you mentioned exactly happened. Never went into loadedTimeRanges?

If possible, you should give us more informations. It can be HysteriaPlayer logs inside your console.

**Comment by Phil0529** [comment]
the stream address is http://180.150.191.88/live/85649.m3u8?bitrate=64&deviceid=a3fdf5e8b6bd32039355758776ac438f

在 2015-10-09 17:58:10，"肖翰程" <xiaohancheng0529@163.com> 写道：
can i reply it in this with the question?

At 2015-10-09 17:50:13, "Saiday" <notifications@github.com> wrote:


You mean the version of iPod is iOS 8.4.1 and iOS 9.1.2 right? Is there any iOS version can work that you've tested?

I'm not sure what not appear you mentioned exactly happened. Never went into loadedTimeRanges?

If possible, you should give us more informations. It can be HysteriaPlayer logs inside your console.

**Comment by saiday** [comment]
So what we know now is something went wrong on iPod with iOS 8.4.1, do you observer any code level doubtful logs or exceptions?

I don't have iPod touch btw.

**Comment by saiday** [comment]
It could be better that you paste HysteriaPlayer logs on this issue.

**Comment by Phil0529** [comment]
the logs  is only    repeat
2015-10-09 18:10:14.653 HyseteriaSamples[801:172616] The operation could not be completed
2015-10-09 18:10:14.688 HyseteriaSamples[801:172616] current item changed
2015-10-09 18:10:14.851 HyseteriaSamples[801:172616] index: 1 is about to play

**Comment by Phil0529** [comment]
and i have the breakpoint  to check  find that -->the kvo observer  keyPath id not find "loadedTimeRanges" ---> only "rate"  and "currentItem"

**Comment by Phil0529** [comment]
and where are you from

**Comment by Phil0529** [comment]
and I find  maybe the reason is the version  means that the stream url is not available below the 9.0 the stream url  
http://hls.qd.qingting.fm/live/85651.m3u8?deviceid=b25036dd51334233ab2bebc5f41c09c8&bitrate=24
-> m3u8 format  where the question; can you vertify it to solve it.

**Comment by saiday** [comment]
@Phil0529 Oh ok, It seems like under iOS 9 there's some bug with file-based media (HysteriaPlayer use it to play empty sound before your first item been initiated) and HTTP Live Streaming (which you are using), so there's a quick fix for you.

Find `- (void)playEmptySound` in HysteriaPlayer.m,  modify source code like this
```
- (void)playEmptySound
{
    //play .1 sec empty sound
    self.audioPlayer = [[AVQueuePlayer alloc] init];
//    NSBundle *bundle = [NSBundle bundleForClass:[self class]];
//    NSString *filepath = [bundle pathForResource:@"point1sec" ofType:@"mp3"];
//    if ([[NSFileManager defaultManager]fileExistsAtPath:filepath]) {
//        self.isInEmptySound = YES;
//        AVPlayerItem *playerItem = [AVPlayerItem playerItemWithURL:[NSURL fileURLWithPath:filepath]];
//        self.audioPlayer = [AVQueuePlayer queuePlayerWithItems:[NSArray arrayWithObject:playerItem]];
//    }
}
```

I'm patching a commit to let user had a opportunity to disable empty sound playing.
I'm from Taiwan, btw.

Ref: iOS 9 release note
> AVQueuePlayer now supports a mixture of file-based media and HTTP Live Streaming media in its queue. Prior to this, you had to ensure that all items in the queue were of the same type.

**Comment by Phil0529** [comment]
thx it's ok

**Comment by Phil0529** [comment]
我是大陸的.開發ios時間不是很長,所以遇到這個問題,順便問一句你為什麼要預置播放這個空聲音了?

**Comment by jiayuzhang** [comment]
Same question here, why pre-play an empty sound file here? A sort of way to boost initialization of the underlying AVPlayer??
