### ISSUE TITLE
 HysteriaPlayer OS X Compatibility 

### ISSUE THREAD

**Issue by manikkalra** [StreetVoice/HysteriaPlayer#92]
Hello, 

Is there anyway to use the library on OS X? It would be immensely helpful for me!

**Comment by saiday** [comment]
@manikkalra I thought HysteriaPlayer can work on OSX, yet I haven't tried.
All framework dependencies are OSX compatible, If you tried, please inform us.

**Comment by manikkalra** [comment]
This is what I get when I try to install via CocoaPods: 

[!] The platform of the target `AppName` (OS X 10.10) is not compatible with `HysteriaPlayer (2.1.3)`, which does not support `osx`.

**Comment by manikkalra** [comment]
Also, AVAudioSession does not exist on iOS. HysteriaPlayer.m has a lot of references to AVAudioSession and some iOS specific code which is preventing me to compile it on OS X.

**Comment by saiday** [comment]
Thank you for your prompt PR, it's awesome.

FYI, I update the `podspec`, hence HysteriaPlayer is OS X compatible [on CocoaPods](https://cocoapods.org/pods/hysteriaplayer) because of your effort
