### ISSUE TITLE
Strange code in playerItemDidReachEnd method.

### ISSUE THREAD

**Issue by dmalyshkin-issart** [StreetVoice/HysteriaPlayer#95]
Method playerItemDidReachEnd has some code which I cannot understand. Could you please describe its logic?

Let's see. If _repeatMode == HysteriaPlayerRepeatModeOff and _shuffleMode == HysteriaPlayerShuffleModeOff then execution falls to the 'else' block listed below:
```
            if (self.audioPlayer.items.count == 1 || !isPreBuffered) {
                NSInteger nowIndex = [CHECK_Order integerValue];
                if (nowIndex + 1 < [self hysteriaPlayerItemsCount]) {
                    [self playNext];
                } else {
                    if (_repeatMode == HysteriaPlayerRepeatModeOff) {
                        [self pausePlayerForcibly:YES];
                        if ([self.delegate respondsToSelector:@selector(hysteriaPlayerDidReachEnd)]) {
                            [self.delegate hysteriaPlayerDidReachEnd];
                        }
                    }
                    [self fetchAndPlayPlayerItem:0];
                }
            }
```
If isPreBuffered is 'NO' then we enter the 'if' block despite of 'self.audioPlayer.items.count' value. And if we have no more items to play -- the next 'if (nowIndex+1 <...' goes to its 'else' part. As a result the next line is always called:
`[self fetchAndPlayPlayerItem:0];`

What is this line of code doing? Why does it always start to play item #0 even if there are no any items?
Could you please describe this place in more details?

**Comment by saiday** [comment]
So which part confuse you? Why `[self fetchAndPlayPlayerItem:0];`?

We make a playback behaviour that when you reach the end of your list, roll back to the first item.
And the point is 5 lines above, if there's no repeat wanted, `[self pausePlayerForcibly:YES];` indicates player would not play when item gets ready to play.

**Comment by dmalyshkin-issart** [comment]
Thank you for the answer and clarification.
Yes, this line confuses me. It looks strange for me to call it without any condition.
But it seems the bug somewhere in our part, I'm still looking. Thank you for the help.

**Comment by saiday** [comment]
Close this issue, you can reopen it anytime.
